// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHz3PCnCwUGG5S3XPpUZ33AT6Gco9l0sk',
    appId: '1:298887052643:web:5c1e7937df1e39198a2756',
    messagingSenderId: '298887052643',
    projectId: 'rental-car-b620c',
    authDomain: 'rental-car-b620c.firebaseapp.com',
    storageBucket: 'rental-car-b620c.appspot.com',
    measurementId: 'G-2NHC93TBHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATCy2Q5k9z3QI8U2HEVDw77cD9tmx7Xw8',
    appId: '1:298887052643:android:a80b3df7d315cebc8a2756',
    messagingSenderId: '298887052643',
    projectId: 'rental-car-b620c',
    storageBucket: 'rental-car-b620c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5pNhP4oRCLFEJe8Tw5SDaJgLi6Fw-cWs',
    appId: '1:298887052643:ios:e6478a8fd471f07e8a2756',
    messagingSenderId: '298887052643',
    projectId: 'rental-car-b620c',
    storageBucket: 'rental-car-b620c.appspot.com',
    iosBundleId: 'com.example.rentalCar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5pNhP4oRCLFEJe8Tw5SDaJgLi6Fw-cWs',
    appId: '1:298887052643:ios:e6478a8fd471f07e8a2756',
    messagingSenderId: '298887052643',
    projectId: 'rental-car-b620c',
    storageBucket: 'rental-car-b620c.appspot.com',
    iosBundleId: 'com.example.rentalCar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHz3PCnCwUGG5S3XPpUZ33AT6Gco9l0sk',
    appId: '1:298887052643:web:d8be2aa46987c7c08a2756',
    messagingSenderId: '298887052643',
    projectId: 'rental-car-b620c',
    authDomain: 'rental-car-b620c.firebaseapp.com',
    storageBucket: 'rental-car-b620c.appspot.com',
    measurementId: 'G-FY3SR02SKT',
  );

}